### ISSUE TITLE
Roadmap v4.0.0 [Will be worked on once pandemic ends 😬]

### ISSUE THREAD

**Issue by harshzalavadiya** [harshzalavadiya/react-multi-select-component#131]
### Why

This component was written a year ago (when I was just starting to get hang of react) so there were many things that I didn't knew back then so after revisiting codebase today I realized that there are so many things that can be improved and that might make this tiny component *even better*

### TODO

- [x] Utilize React Context API instead of Prop Drilling (might reduce bundle size even more)
- [ ] ~Proper naming convention for all `prop` and `className`~ (kept as it is since this might break things and it's nominal)
- [x] Clean up unnecessary CSS properties
- [ ] ~Dark Mode (Maybe)~ (cancelled because overriding variables are easy using css-variables)

Most changes will be done internally so migration from v3 to v4 should be mostly smooth so external changes might only be at renaming props and classes if you directly target them

Since I have a seprate job (that does not pay me to maintain this) so it might be hard to have proper fixed date for this 😅

**Comment by chenshuiluke** [comment]
@harshzalavadiya hey man, thanks for working on this :)
